name: Compile Go for Apple Silicon

## FIXME: Run the build step on ubuntu-latest,
##        then run the signing and uploading on macos-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  GOARCH: arm64
  GOOS: darwin

jobs:

  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    continue-on-error: false
    outputs:
      target_run_id:
        description: "Workflow Step Identifier"
        value: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Caching
        uses: actions/cache@v2
        with:
          path: |
            .cache
          key: ${{ runner.os }}-cache-${{ hashFiles('.cache/**') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Pull Docker Image
        run: docker pull didstopia/go-compiler:latest
      - name: Build Docker Image
        run: docker build --rm -t didstopia/go-compiler:latest .
      - name: Compile Go
        run: docker run --rm -v ${PWD}/.cache:/tmp -v ${PWD}/data:/data -e GOARCH=${GOARCH} -e GOOS=${GOOS} didstopia/go-compiler:latest
      - name: Compress Binaries (unsigned)
        run: |-
          zip -rq go-binaries-unsigned.zip data/
          ls -la
          ls -la data
      - name: Upload Binaries (unsigned)
        uses: actions/upload-artifact@v2
        with:
          name: go-binaries-unsigned
          path: go-binaries-unsigned.zip

  sign:
    needs: compile
    runs-on: macos-latest
    timeout-minutes: 15
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Download Binaries (unsigned)
        uses: actions/download-artifact@v2
        with:
          name: go-binaries-unsigned
          path: go-binaries-unsigned.zip
      - name: Decompress Binaries (unsigned)
        run: |-
          unzip go-binaries-unsigned.zip -d data
          ls -la
          ls -la data
      - name: Sign Binaries
        run: ./codesign.sh
      - name: Compress Binaries (signed)
        run: |-
          zip -rq go-binaries-signed.zip data/
          ls -la
          ls -la data
      - name: Upload Binaries (signed)
        uses: actions/upload-artifact@v2
        with:
          name: go-binaries-signed
          path: go-binaries-signed.zip
  
  cleanup:
    needs: [compile, sign]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: true
    steps:
      - name: Cleanup Build Artifacts
        if: ${{ github.event.client_payload.run_id }}
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'debug'
          min_bytes: '0'
          artifact_name: 'go-binaries-unsigned'
          run_id: '${{ needs.generate.outputs.target_run_id }}'
